### ISSUE TITLE
False Alert with pre-commit module

### ISSUE THREAD

**Issue by segfaultdoc** [depcheck/depcheck#320] opened 2019-02-14 03:33 UTC
1. JSON:  {
   "dependencies":[
   ],
   "devDependencies":[
      "pre-commit"
   ],
   "missing":{
   },
   "using":{
      "eslint-config-airbnb-base":[
         "/Users/zsherwani/my_projects/api.userservice/.eslintrc.yml"
      ],
      "eslint-plugin-import":[
         "/Users/zsherwani/my_projects/api.userservice/.eslintrc.yml"
      ],
      "eslint":[
         "/Users/zsherwani/my_projects/api.userservice/.eslintrc.yml",
         "/Users/zsherwani/my_projects/api.userservice/package.json"
      ],
      "express":[
         "/Users/zsherwani/my_projects/api.userservice/app.js",
         "/Users/zsherwani/my_projects/api.userservice/src/routes/customers.js",
         "/Users/zsherwani/my_projects/api.userservice/src/routes/jeffeUsers.js"
      ],
      "body-parser":[
         "/Users/zsherwani/my_projects/api.userservice/app.js"
      ],
      "aws-sdk":[
         "/Users/zsherwani/my_projects/api.userservice/app.js",
         "/Users/zsherwani/my_projects/api.userservice/src/database/Database.js",
         "/Users/zsherwani/my_projects/api.userservice/src/modules/Utilities.js"
      ],
      "depcheck":[
         "/Users/zsherwani/my_projects/api.userservice/package.json"
      ],
      "dotenv":[
         "/Users/zsherwani/my_projects/api.userservice/src/database/Database.js"
      ],
      "lodash":[
         "/Users/zsherwani/my_projects/api.userservice/src/middlewares/interceptors/UserInterceptor.js",
         "/Users/zsherwani/my_projects/api.userservice/src/middlewares/validators/TokenValidator.js",
         "/Users/zsherwani/my_projects/api.userservice/src/middlewares/validators/SchemaValidator.js"
      ],
      "jsonwebtoken":[
         "/Users/zsherwani/my_projects/api.userservice/src/middlewares/validators/TokenValidator.js",
         "/Users/zsherwani/my_projects/api.userservice/src/models/user.js"
      ],
      "joi":[
         "/Users/zsherwani/my_projects/api.userservice/src/middlewares/validators/SchemaValidator.js",
         "/Users/zsherwani/my_projects/api.userservice/src/schemas/customerSchema.js",
         "/Users/zsherwani/my_projects/api.userservice/src/schemas/jeffeSchema.js"
      ],
      "bcrypt":[
         "/Users/zsherwani/my_projects/api.userservice/src/models/user.js"
      ],
      "request":[
         "/Users/zsherwani/my_projects/api.userservice/test/test.js"
      ]
   },
   "invalidFiles":{
   },
   "invalidDirs":{
   }
}

2. The pre-commit devdependency is a false alert

3. This package is a "pre-commit hook installer", it gets installed in the .git directory, seems as though this is being skipped over.

https://www.npmjs.com/package/pre-commit

**Comment by rumpl** [comment] 2019-02-14 10:12
Hey @segfaultdoc, thanks for reporting this, the pre-commit is reported as unused because it's not used in the code, we would need to do some special things in order to manage this package, for now you can use the `--ignores` flag so that it doesn't report it as unused.

Cheers

**Comment by VincentLanglet** [comment] 2019-11-03 16:13
@rumpl Duplicate of https://github.com/depcheck/depcheck/issues/261

**Closed** 2019-11-03 18:04 UTC
Labels: feature, refinement
