### ISSUE TITLE
Depcheck started returning incorrect unused dependencies without any changes

### ISSUE THREAD

**Issue by tm-slavik57** [depcheck/depcheck#687] opened 2021-12-14 10:34 UTC
### Bug Description

I'm not sure it's related, but since of today depcheck started reporting incorrect unused dependencies.

### Versions

- `node -v`: 14.16.1
- `npm -v`: 6.14.12
- `depcheck --version`: 1.4.2

### Extra info

We are using `npx depcheck` and until yesterday it worked in our CI, starting from today it stopped working.
We didn't change anything, and on the same commit, it worked yesterday it stopped working today.

I tried to figure out what's wrong so I ran the depcheck locally on my laptop and it worked.
I then looked at the `depcheck` installed globally on my laptop and saw it's from July.
At this point the depcheck version is `1.4.2`

Running `npx depcheck` resulted in this output:
```
$ npx depcheck --config=./ci/.depcheckrc
No depcheck issue
```

After that I reinstalled it globally using:
```
$ npm install -g depcheck
C:\Users\Slavas\AppData\Roaming\npm\depcheck -> C:\Users\Slavas\AppData\Roaming\npm\node_modules\depcheck\bin\depcheck.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules\depcheck\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
The depcheck version didn't change and remained `1.4.2`

Now running the check command fails:
```
$ npx depcheck --config=./ci/.depcheckrc
Unused dependencies
* aws-sdk
* express
Unused devDependencies
* @types/chai
* @types/kafkajs
* chai
* chai-as-promised
* http-status-codes
* kafkajs
```

My assumption is when running `npx` is that it used the cached version that was on my laptop and after reinstalling it, it downloaded a new version and stopped working.

The thing I don't understand is that `depcheck -v` returned `1.4.2` both while the behaviour changed.

**Comment by filipw01** [comment] 2021-12-14 10:39
It's not just you, `@babel/parser` version 7.16.5 broke it, released 12 hours ago
Workaround, is to lock it using yarn resolutions
```
  "resolutions": {
    "depcheck/@babel/parser": "7.16.4"
  },
```

**Comment by tm-slavik57** [comment] 2021-12-14 11:59
> It's not just you, `@babel/parser` version 7.16.5 broke it, released 12 hours ago Workaround, is to lock it using yarn resolutions
> 
> ```
>   "resolutions": {
>     "depcheck/@babel/parser": "7.16.4"
>   },
> ```

Do I have to make depcheck part of the `package.json` dev dependencies for it to work or is there a way to make it work with `npx` as well?

**Comment by filipw01** [comment] 2021-12-14 12:05
> > It's not just you, `@babel/parser` version 7.16.5 broke it, released 12 hours ago Workaround, is to lock it using yarn resolutions
> > ```
> >   "resolutions": {
> >     "depcheck/@babel/parser": "7.16.4"
> >   },
> > ```
> 
> Do I have to make depcheck part of the `package.json` dev dependencies for it to work or is there a way to make it work with `npx` as well?

For this exact solution you need to use `yarn` and have `depcheck` as your dependency. I'm not aware of any manual dependency locking mechanism for `npx`. For `npm` [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) might work, but I haven't tried it personally

**Comment by zhoushoujian** [comment] 2021-12-30 02:35
I tried 'npm npm-force-resolutions', it doesn't work, because npm-force-resolutions only install babel in my npm project, not in depCheck project, so in  depCheck folder, it has its own node_modules and only its babel. In fact, my npm project needn't babel, with npm npm-force-resolutions, it will install babel in my npm project.
By the way, as my npm project package, user may use npm or pnpm to install, so we must guarantee npm work correctly. Maybe we can lock babel version until it fixed the bug.

**Comment by karlhorky** [comment] 2022-01-09 15:39
@rumpl can you release a new version locked to `"@babel/parser": "7.16.4"`?

**Comment by karlhorky** [comment] 2022-01-09 17:00
In the meantime, for anyone looking for a fixed version of `depcheck` (eg if you cannot use resolutions for whatever reason), change your version in your `package.json` to the version below.

We locked the version of `@babel/parser` to `7.16.4` and ran the `compile` and `component` scripts. Check the repo here: https://github.com/upleveled/depcheck

```
  "depcheck": "upleveled/depcheck#45494b8eec5fa6b4d4c512f2b069f8ba3111ab23",
```

**Comment by rumpl** [comment] 2022-01-09 19:06
I just released [version 1.4.3](https://www.npmjs.com/package/depcheck/v/1.4.3)

**Comment by rumpl** [comment] 2022-01-09 19:08
@karlhorky thanks, next time feel free to open a PR 👍

**Comment by karlhorky** [comment] 2022-01-09 22:10
@rumpl Thanks for the quick response and publish! 🙌 Good idea about the PR - I definitely try to do this most times, and will continue to do this in the future.

**Comment by znarf** [comment] 2022-01-10 10:13
@rumpl @karlhorky I don't see the rationale for fixing this particular dependency, and not others like say `@babel/traverse`. We could end up with inconsistencies.

Now that it's fixed, what will be the strategy moving forward to update it?

I think https://github.com/depcheck/depcheck/pull/692 was a better answer to the problem.

**Comment by rumpl** [comment] 2022-01-10 10:18
I only followed this from afar but from what I can tell the issue is that:

1. babel/parser released a new patch version that had some backward incompatible changes
2. `npx` doesn't read the lockfile for some reason

`1.` is fine I guess, happens all the time, `2.` is more problematic since it would seem that there is no way to make this work reliably. 

Best strategy would be to update all `@babel` to latest and merge #692 I guess

**Comment by karlhorky** [comment] 2022-01-10 10:19
> I don't see the rationale for fixing this particular dependency
>
> We could end up with inconsistencies

This was only a short-term hotfix, because the latest published version of `depcheck` was broken for new users - it was reporting false positives. Locking this dependency is a short-term workaround for the problem, which did not show any other problems in my testing.

> Now that it's fixed, what will be the strategy moving forward to update it?
>
> I think #692 was a better answer to the problem.

As mentioned above, it's not a longer-term fix, so it still needs to be resolved in a more permanent way. This is also why this current issue should still be open.

**Comment by rumpl** [comment] 2022-01-10 10:20
Dammit, I didn't read the #692 since it was red but it's because codecov is just broken, I'll remove it...

**Comment by znarf** [comment] 2022-01-10 10:32
> 2. npx doesn't read the lockfile for some reason

The lockfile is currently not published in the package, and that's right, it should not. npx only relies on package.json.
https://stackoverflow.com/questions/44546718/should-package-lock-json-also-be-published 

For a library/package, I would say it should even not be commited to the git repository.

**Comment by rumpl** [comment] 2022-01-10 10:35
> The lockfile is currently not published in the package, and that's right, it should not. npx only relies on package.json.

Ok, today I learned something and I cannot imagine why they would do that...

> For a library/package, I would say it should even not be commited to the git repository.

It should, why wouldn't someone want to lock the dependencies?

**Comment by znarf** [comment] 2022-01-10 10:44
>> For a library/package, I would say it should even not be committed to the git repository.

> It should, why wouldn't someone want to lock the dependencies?

As we just saw, it's not used and not published, so it could be confusing. If it's only used in dev environment, is it worth it? You can check, libraries are commonly not committing their package-lock.json https://github.com/eslint/eslint   https://github.com/vercel/next.js https://github.com/facebook/react

**Comment by rumpl** [comment] 2022-01-10 10:54
next.js and react use yarn, found [this](https://www.twilio.com/blog/lockfiles-nodejs), kinda explains the thing...

Well... Okay then #696

**Comment by znarf** [comment] 2022-01-10 11:19
> next.js and react use yarn

oh, true! and in the case of React and Next.js, the yarn.lock is committed

**Comment by ahutch95** [comment] 2022-04-05 22:39
I seem to be experiencing this same issue again. Is it possible another dependency has been updated?

**Comment by karlhorky** [comment] 2022-08-15 21:47
I guess this is not stale, right?

**Comment by karlhorky** [comment] 2023-01-08 07:54
Not stale?

**Comment by znarf** [comment] 2023-01-23 08:40
@karlhorky That precise one was fixed in https://github.com/depcheck/depcheck/pull/692, this issue should be closed.

**Closed** 2023-01-23 08:41 UTC
Labels: bug, wontfix

**Comment by karlhorky** [comment] 2023-01-23 09:39
Was #692 actually merged?

Also, I don't remember too much about this issue now, but the last comments above say that #692 was not an ideal fix and only short-term...
