### ISSUE TITLE
Support .depcheckrc or depcheck.config.js config file

### ISSUE THREAD

**Issue by VincentLanglet** [depcheck/depcheck#318] opened 2019-02-07 15:51 UTC
It would be greate to be able to set a config in .depcheckrc instead of adding argument every time I use the command.

**Comment by rumpl** [comment] 2019-02-14 10:14
Indeed, I think this would be a nice thing to have, we'll get to it time permitting.

**Comment by rumpl** [comment] 2019-02-14 10:26
Closing since duplicate of #162

**Closed by rumpl** 2019-02-14 10:26 UTC
Labels: feature
