### ISSUE TITLE
False Alerts (multiple)

### ISSUE THREAD

**Issue by Perlkonig** [depcheck/depcheck#310] opened 2019-02-02 19:10 UTC
- @types/jest
- acorn
- ts-jest
- webpack-cli

I'm working in Typescript. The Jest tests won't work unless `ts-jest` and `@types/jest` are installed. `Webpack-cli` is needed for my build process, and `acorn` is required by `webpack-cli`.

Here's the output of `depcheck --json`:

```json
{
	"dependencies": [],
	"devDependencies": ["@types/jest", "acorn", "ts-jest", "webpack-cli"],
	"missing": {},
	"using": {
		"ajv": ["D:\\github\\renderer\\build\\index.js", "D:\\github\\renderer\\src\\index.ts", "D:\\github\\renderer\\test\\index.test.ts"],
		"svg.js": ["D:\\github\\renderer\\build\\index.js", "D:\\github\\renderer\\src\\index.ts"],
		"jest": ["D:\\github\\renderer\\package.json"],
		"json-schema-to-typescript": ["D:\\github\\renderer\\package.json"],
		"tslint": ["D:\\github\\renderer\\package.json"],
		"typescript": ["D:\\github\\renderer\\package.json", "D:\\github\\renderer\\webpack.config.js"],
		"webpack": ["D:\\github\\renderer\\package.json"],
		"ts-loader": ["D:\\github\\renderer\\webpack.config.js"]
	},
	"invalidFiles": {
		"D:\\github\\renderer\\build\\index.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\renderer.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\sheet.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\renderers\\index.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\renderers\\default.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\sheets\\default.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\build\\sheets\\index.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)",
		"D:\\github\\renderer\\src\\schema.d.ts": "Error: Debug Failure. Output generation failed\n    at transpileModule (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105174:29)\n    at Object.transpile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\typescript\\lib\\typescript.js:105182:22)\n    at parseTypescript (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\parser\\typescript.js:24:29)\n    at _fs.default.readFile (C:\\Users\\aaron\\AppData\\Roaming\\npm\\node_modules\\depcheck\\dist\\check.js:77:17)\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)"
	},
	"invalidDirs": {}
}
````

**Comment by rumpl** [comment] 2019-02-02 19:47
@Perlkonig thanks for reporting this.

Is this a duplicate of https://github.com/depcheck/depcheck/issues/189 ?

If not, would you be so kind and make a minimal example of what is going on in your case ?

Cheers!

**Comment by Perlkonig** [comment] 2019-02-03 14:57
It looks like that issue is the problem with `@types/jest`. I don't understand well enough to say if that's the problem with `ts-jest`. If there's a way to add ignored packages, then `webpack-cli` and `acorn` are a non-issue.

Jest is the testing framework. It gets called by an npm script:

```json
    "scripts": {
        "build": "npm run tslint && npm run build-ts",
        "build-ts": "tsc",
        "test": "jest --forceExit --detectOpenHandles --verbose --config jest.config.js",
```

Here's `jest.config.js`:

```js
module.exports = {
    globals: {
        'ts-jest': {
            tsConfig: 'tsconfig.json'
        }
    },
    'coverageDirectory': undefined,
    'collectCoverage': false,
    'collectCoverageFrom': [
        '**/src/**/*.{ts,js}'
    ],
    moduleFileExtensions: [
        'ts',
        'js'
    ],
    transform: {
        '^.+\\.(ts|tsx)$': 'ts-jest'
    },
    testMatch: [
        '**/test/**/*.test.(ts|js)'
    ],
    testEnvironment: 'node'
};
```

This is the only place that `ts-jest` gets explicitly mentioned.

Repo is here: https://github.com/AbstractPlay/renderer.

**Comment by rumpl** [comment] 2019-11-03 19:46
not stale

**Closed** 2020-03-16 21:49 UTC
Labels: bug, wontfix

**Comment by patcon** [comment] 2020-07-31 21:13
`webpack-cli` might be an issue because normally a CLI command would get silenced by using it in `scripts` key of package.json, and using `bin` special. But `webpack-cli` offers a command bin called `webpack`, so that might confuse things?

**Comment by belaaiza** [comment] 2021-02-03 17:03
I'm facing a false alert for @types/jest too. Should this have been resolved by https://github.com/depcheck/depcheck/issues/163? Or it is another problem considering that jest is not explicitly imported?

**Comment by kaaax0815** [comment] 2021-05-05 18:27
I'm facing a false alert for `@types/node`. I need to have it installed to use `console.log`
