### ISSUE TITLE
Error: toString failed

### ISSUE THREAD

**Issue by harshjv** [depcheck/depcheck#100] opened 2016-02-21 06:43 UTC
`Error: toString failed` when used with `node v4.3.1`

`$ depcheck`

```
buffer.js:388
    throw new Error('toString failed');
    ^

Error: toString failed
    at Buffer.toString (buffer.js:388:11)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:378:21)
```

**Comment by lijunle** [comment] 2016-02-21 08:09
Strange, how about `depcheck --json`?

**Comment by harshjv** [comment] 2016-02-21 08:18
Same error with `depcheck --json`

**Comment by lijunle** [comment] 2016-02-21 08:32
It sems related to node.js: https://github.com/nodejs/node/issues/2767

Are there large files in your project?

**Comment by lijunle** [comment] 2016-02-25 14:30
@harshjv do you have any update on this issue? I am going to close this issue if you have no reply in 1 day.

**Comment by veob** [comment] 2016-02-26 08:59
I'm having the same issue. 
Node's version: `v4.4.1`

**Comment by lijunle** [comment] 2016-02-26 09:00
@veob do you have a large file in your project?

**Comment by veob** [comment] 2016-02-26 09:06
Large .js file? I don't think so. I have some .bson, .json files that might be large, but not .js. 
Btw, before crashing `depcheck` runs for, like, 3-5 minutes. 
Maybe it is my project that too large?

**Comment by lijunle** [comment] 2016-02-26 09:07
Depcheck not only read for `.js` file - it *may* read JSON files. How large is your JSON file?

**Comment by veob** [comment] 2016-02-26 09:13
@lijunle 
Nothing larger than 1 Mb.

**Comment by lijunle** [comment] 2016-02-26 09:16
OK, let me assume that 1M in this case.

Besides, how many files under your project folder?

**Comment by veob** [comment] 2016-02-26 09:23
~1400 .js files

**Comment by veob** [comment] 2016-02-26 09:32
Hm. I've just ran `depcheck` in project with ~300 .js files and everything is OK.

**Comment by lijunle** [comment] 2016-02-26 10:20
@veob thanks for your information. I will test offline tonight and revisit here later.

**Comment by lijunle** [comment] 2016-03-04 17:07
@veob Sorry that I tried different ways, however cannot repro this issue.

Are you still getting this exception? Could you provide more information?

- Node version
- NPM version
- OS

**Comment by veob** [comment] 2016-03-09 06:05
node version: `4.1.1`
npm version: `2.14.4`
OS: `Ubuntu 14.04.4 LTS`

Just so you know, It's not critical for me to check dependencies for this particular project and if you wouldn't be able to reproduce and fix this issue, for me personaly it's okay. Don't about other people though.

**Comment by jmealo** [comment] 2016-03-13 23:23
@lijunle I'm having the same issue. I do use ES6/harmony features and generators (koa app). I'm not sure if this impacts anything.

node version: ``4.3.1``
npm version: ``2.14.12``
OS: ``OSX 10.11.3``

**Comment by lijunle** [comment] 2016-03-14 05:40
I am considering it is caused by binary files (either custom binary file or node.js addons). I am not having time to verify it. Could you please help to verify it? Great thanks.

**Comment by jmealo** [comment] 2016-03-15 00:50
@lijunle I'm not sure what you mean. I checked and the biggest JSON file that I had was 1.3MB. I removed that file and still no luck.

**Comment by lijunle** [comment] 2016-03-15 01:28
@jmealo do you have binary files in your project folder? If yes, could you please remove them and re-run depcheck?

**Comment by lijunle** [comment] 2016-06-19 19:32
Hey, everybody here. After release v0.6.3 to npm-check, I don't get similar issues. Does anybody still getting this issue (with newest node.js)?

**Comment by webzepter** [comment] 2016-06-24 19:54
@lijunle I have this issue with v0.6.3

**Comment by mnkhouri** [comment] 2018-08-28 01:10
I'm closing this issue due to no activity in 2 years. Please feel free to open a new issue if this issue is seen again!

**Closed by mnkhouri** 2018-08-28 01:10 UTC
Labels: bug
